### ISSUE TITLE
SDL 1.2 support?

### ISSUE THREAD

**Issue by glebm** [realnc/SDL_audiolib#1]
Thank you for this library, it looks just like what we need for DevilutionX (Diablo 1) to be able to play off the original CD (and stream both actual music and dialogue).

Does this also support SDL 1.2? DevilutionX uses SDL 1.2 for devices that have no SDL2 port

**Comment by realnc** [comment]
SDL 1.x support was removed 5 years ago, I'm afraid.

**Comment by glebm** [comment]
I have found the commit that removes it: https://github.com/realnc/SDL_audiolib/commit/ec429b72b36237c46c31b0cccbfe1eebe139897b

Perhaps it won't be too difficult to bring it back; I can give it a go once I got the SDL2 one working
