### ISSUE TITLE
Does not build in Visual Studio 2019

### ISSUE THREAD

**Issue by glebm** [realnc/SDL_audiolib#15]
This is due to the use of alternative operators, which do not seem to be supported in Visual Studio:

> DecoderDrwav.cpp(56,12): error C2065: 'not': undeclared identifier [C:\projects\devilutionx\_deps\sdl_audiolib-build\SDL_audiolib.vcxproj]

The alternative operators described purpose is fairly obscure: to be compatible with character sets that don't have the `&!~` symbols (from https://en.cppreference.com/w/cpp/language/operator_alternative).

Perhaps the code here could be changed to use the canonical operators?

(full build log: https://ci.appveyor.com/project/AJenbo/devilutionx/builds/38866663)

**Comment by realnc** [comment]
What happens if you add `/permissive-` to the compiler flags?

**Comment by glebm** [comment]
That should work but I think we might need to use canonical operators for GCC6 support anyway

**Comment by realnc** [comment]
These keywords are part of the first C++ standard from 1998. All GCC versions support them.
