### ISSUE TITLE
Data race when a stream is destroyed

### ISSUE THREAD

**Issue by glebm** [realnc/SDL_audiolib#23]
If a stream is destroyed from another thread while it is in the callback function, it should not cause a data race.

Current implementation sometimes calls `SDL_RWops` `close` while reading from it.

TSAN report: https://gist.githubusercontent.com/glebm/f3243cb99489245822160434943a81ce/raw/1e6b4c759a1e418486e9c3f87ef55e01e14a60dd/gistfile1.txt

**Comment by glebm** [comment]
For reference, here is how SDL does something similar for an audio device:

Outer loop checks for the device shutdown flag:

https://github.com/libsdl-org/SDL/blob/424bbaec069f0d94857095dcdfacba6246282936/src/audio/SDL_audio.c#L724-L726

Buffer filling is under a per-device lock:

https://github.com/libsdl-org/SDL/blob/424bbaec069f0d94857095dcdfacba6246282936/src/audio/SDL_audio.c#L747-L754

**Comment by realnc** [comment]
I pushed some improvements. However, note that the library is not thread-safe. It should now be re-entrant with these changes and `Stream` is now documented as such, but never access the same `Stream` object from different threads without synchronizing that access:

```none
 * All public functions of this class will lock the SDL audio device when they are called, and
 * unlock it when they return. Therefore, it is safe to manipulate a Stream that is currently
 * playing without having to manually lock the SDL audio device.
 *
 * This class is re-entrant but not thread-safe. You can call functions of this class from different
 * threads only if those calls operate on different objects. If you need to control the same Stream
 * object from multiple threads, you need to synchronize access to that object. This includes Stream
 * destruction, meaning you should not create a Stream in one thread and destroy it in another
 * without synchronization.
```

**Comment by glebm** [comment]
Thanks! The update seems to fix the issue!
We only call methods on Stream from the main thread, so that should be OK

The issue was that Aulib didn't use `SDL_RWops` safely (`SDL_RWops` generally is not thread-safe), as it called `close` at the same time as `read`.
