### ISSUE TITLE
Platforms without any exceptions support

### ISSUE THREAD

**Issue by glebm** [realnc/SDL_audiolib#36]
I'm trying to port DevilutionX to the original XBox NXDK

This platform does not support exceptions at all, which results in:

```
lld: error: undefined symbol: ___std_terminate
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj):(int `public: __thiscall std::exception::exception(class exception::dtor$2 const &)'::`1'::dtor$2)
```

Not sure what the best way to resolve this is.

**Comment by realnc** [comment]
There's no` std::terminate()`? That's weird. So if you call that directly, you get the same error?

**Comment by glebm** [comment]
Yeah, there is no exceptions support at all and it looks like `std::terminate` is part of the exceptions support.

We'd need to call `std::exit` or `std::abort` instead.

**Comment by realnc** [comment]
Does the obvious workaround of simply providing an implementation of `std::terminate` work?

**Comment by glebm** [comment]
Defining anything in the `std` namespace is UB IIRC.
It would probably need to be compiler-specific (`___std_terminate`) and while it may work, it doesn't seem like a good workaround.

I think the solution in https://github.com/realnc/SDL_audiolib/pull/33 is a better option here.
I can imagine in many cases sound is the only thing threads are used for (e.g. this is the case for DevilutionX single player), so failing to create a mutex is not necessarily a fatal error.

Alternatively, there could be a CMake option to replace that one `throw` with `std::exit`.

**Comment by realnc** [comment]
> Defining anything in the `std` namespace is UB IIRC. It would probably need to be compiler-specific (`___std_terminate`) and while it may work, it doesn't seem like a good workaround.

It seems like an excellent workaround, until fixed in the SDK itself, at which point you should get a link error and can then remove it again. I looked at https://github.com/XboxDev/nxdk/issues and nobody has reported the issue yet though.

Defining things in `std` may be UB, but at this point you're implementing your own `std` missing function that should be there to begin with.

**Comment by glebm** [comment]
I tried the workaround but it doesn't work because there are some other undefined symbols as well:

```
lld: error: undefined symbol: __CxxThrowException@8
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj):(public: __thiscall SdlMutex::SdlMutex(void))

lld: error: undefined symbol: ___std_terminate
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj):(int `public: __thiscall std::exception::exception(class exception::dtor$2 const &)'::`1'::dtor$2)

lld: error: undefined symbol: ___CxxFrameHandler3
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj):(___ehhandler$??0exception@std@@QAE@ABV01@@Z)
```

Defining `std::terminate` leads to duplicate symbol definition.

> I looked at [XboxDev/nxdk/issues](https://github.com/XboxDev/nxdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and nobody has reported the issue yet though.

There is this issue https://github.com/XboxDev/nxdk/issues/463

**Comment by glebm** [comment]
Putting aside the lack of a workaround, does this really need to be an exception?

You said in https://github.com/realnc/SDL_audiolib/pull/33#issuecomment-1162709310:

>  Locking is not optional. If a lock cannot be acquired, the application should shut down since something is seriously broken. The exception that is thrown simply gives applications the opportunity to do a more graceful shutdown. It's not a condition that can just be logged and then have execution resumed.

However, multi-threading is not a critical feature for a lot of the applications.

DevilutionX can run perfectly well on a single thread in single player (just without audio).

I don't think SDL_audiolib should be deciding that for the application.

Can you please reconsider merging #33 instead?

**Comment by realnc** [comment]
Does the `improve-exceptions` branch work? 8d11c63f9d2206e8bae6e76e5b232bbdf5960609 is the relevant commit.

**Comment by glebm** [comment]
Hmm, it doesn't work with that branch

```
-- Performing Test HAVE_EXCEPTIONS - Failed
```

```
lld: error: undefined symbol: ___std_terminate
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj)

lld: error: undefined symbol: ___CxxFrameHandler3
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj):(___ehhandler$??0SdlMutex@@QAE@XZ)
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj):(___ehhandler$?lock@SdlMutex@@QAEXXZ)
>>> referenced by libSDL_audiolib.lib(SdlMutex.cpp.obj):(___ehhandler$?unlock@SdlMutex@@QAEXXZ)
```

Perhaps `set_source_files_properties` should not be called if the exceptions test fails.

**Comment by glebm** [comment]
With https://github.com/realnc/SDL_audiolib/pull/37 it links!
