### ISSUE TITLE
Equivalent to `Mix_SetPanning`

### ISSUE THREAD

**Issue by glebm** [realnc/SDL_audiolib#6]
What is the equivalent to `Mix_SetPanning` in SDL_audolib?

```c++
Mix_SetPanning(channel, left, 255 - left);
```

**Comment by realnc** [comment]
I'll add a `setStereoPosition()` function that accepts a value between -1.0 (all the way to the left) and +1.0 (all the way to the right), which 0 meaning "center."

**Comment by realnc** [comment]
Added in 616389862b5bc15d59b571ceb9f935be7e47ee03. This is simple attenuation-based panning suitable for mono streams, but maybe not for stereo streams. If you set a stereo stream to play all the way to the right for example, the left channel will become inaudible and only the right channel is heard.

Might add a way to enable/specify a mixing strategy for stereo streams later on if needed.

**Comment by glebm** [comment]
I've realized that DevilutionX `Mix_SetPanning` call completely disables one of the channels while adjusting the volume of the other channel:

https://github.com/diasurgical/devilutionX/blob/281533e82d467231a08262f460b032ee253f1371/Source/utils/soundsample.cpp#L56-L57

The new `setStereoPosition` function does not appear to allow for this

**Comment by glebm** [comment]
Actually I guess I could also call `setVolume` and call `setStereoPosition` with either `-1` or `1`

**Comment by glebm** [comment]
Actually, no, I have no idea what's going on there

**Comment by glebm** [comment]
All good now, I think, kudos to @theBigMuh
